// Code generated by mockery v2.47.0. DO NOT EDIT.

package ghui

import mock "github.com/stretchr/testify/mock"

// MockViewer is an autogenerated mock type for the Viewer type
type MockViewer struct {
	mock.Mock
}

type MockViewer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViewer) EXPECT() *MockViewer_Expecter {
	return &MockViewer_Expecter{mock: &_m.Mock}
}

// View provides a mock function with given fields:
func (_m *MockViewer) View() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockViewer_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockViewer_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
func (_e *MockViewer_Expecter) View() *MockViewer_View_Call {
	return &MockViewer_View_Call{Call: _e.mock.On("View")}
}

func (_c *MockViewer_View_Call) Run(run func()) *MockViewer_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViewer_View_Call) Return(_a0 string) *MockViewer_View_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewer_View_Call) RunAndReturn(run func() string) *MockViewer_View_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockViewer creates a new instance of MockViewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViewer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViewer {
	mock := &MockViewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
